version: '3.8'
services:
  users_management_service:
    build:
      context: ./users_management_service
      dockerfile: Dockerfile
    volumes:
      - ./users_management_service:/users_management_service_dockerized:cached  # Corrected bind mount
    ports:
      - "8000:8000"
    image: users_management_service:user_management
    container_name: users_management_service
    command: python manage.py runserver 0.0.0.0:8000

  chat_service:
    build:
      context: ./chat_service
      dockerfile: Dockerfile
    volumes:
      - ./chat_service:/chat_service_dockerized:cached  # Corrected bind mount
    ports:
      - "8002:8000"
    image: chat_service:chat
    container_name: chat_service
    command: python manage.py runserver 0.0.0.0:8002
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
