name: Lint and Format Check

on: [push, pull_request]

jobs:
  lint:
    name: Lint and Format (black + flake8)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8

      - name: Check code formatting with black
        run: |
          black --check chat-service users-management-service translation-service

      - name: Run flake8 linter
        run: |
          flake8 chat-service users-management-service translation-service --count --select=E9,F63,F7,F82 --show-source --statistics
